# Generated by Django 5.2.13 on 2026-04-24 18:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0003_category_tag_post_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('author_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=230, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='books/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('status', models.CharField(choices=[('lendo', 'Lendo'), ('lido', 'Lido'), ('quero_ler', 'Quero ler')], db_index=True, default='quero_ler', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='leitura.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='books', to='leitura.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
